/**
* @author: John Schultz
* @date: 2017-06-05
* @description: Controller for the admin/manager component to manager the game.
* @log:
* ----------------------------------------------------------------------------
* Developer       Date          Description
* ----------------------------------------------------------------------------
* John Schultz    2017-06-05    Newly created
*/
public with sharing class AdminController {

}